Lesson4
HelenRaven/TestGuru pull request #4
Opened 2020-12-07 09:14 UTC by HelenRaven

- Изменила модели и миграции для них
- Добавила seed
- Добавила метод для класса Test
- Добавила метод для инстанса User

2020-12-07 20:08 UTC, BubuntuClu requested changes

2020-12-07 20:08 UTC, BubuntuClu commented on app/models/answer.rb
> +	belongs_to :question
сделай настройку в IDE чтобы табы заменялись на 2 пробела

2020-12-07 20:08 UTC, BubuntuClu commented on app/models/test.rb
> +    self.joins('JOIN categories ON tests.category_id = categories.id')
ты добавила ассоциацию категория, это значит что ты можешь ее использовать в запросах, `joins(:category)`

2020-12-07 20:08 UTC, BubuntuClu commented on app/models/user.rb
> +	def passed_tests_with_level(level)
с отступами беда

2020-12-07 20:08 UTC, BubuntuClu commented on app/models/user.rb
> +end
так же в IDE настрой добавление пустой строки в конец файла

2020-12-07 20:08 UTC, BubuntuClu commented on db/migrate/20201204133551_create_questions.rb
> +    	t.boolean :check, default: false
за что будет отвечать это поле?

2020-12-07 20:08 UTC, BubuntuClu commented on db/seeds.rb
> +Result.create(test_id: test.id, user_id: 1)
убери жесткую привязку к ID

2020-12-08 04:12 UTC, HelenRaven commented
1. Мерджить ветку Lesson2 не буду, удалю ее

2. Как (в моем представлении) все это будет работать:

  - у теста есть булев атрибут abc, с помощью него буду определять - тест на подсчет количества правильных ответов или на определение наиболее часто встречающегося ответа.
  - у вопроса есть булев атрибут check, с помощью него определяю, как нужно отрисовать вопрос: с помощью чекбоксов, или с помощью раунд боксов (т.е. может пользователь выбирать несколько вариантов или только один).

У теста типа abs все вопросы всегда будут с выбором одного ответа.
У тестов типа НЕabc вопросы могут быть разные: несколько правильных вариантов ответа (рисуем чекбокс), только один правильный вариант ответа (рисуем раундбокс)
но даже если правильный всего 1 вариант, этот вопрос можно отрисовать чекбоксами (если стоит соответствующий флаг)

Подсчет: вопросы, где нужно выбрать несколько вариантов, засчитываются, только если все варианты выбраны верно (и 
                ничего лишнего не отмечено). 
               вопросы с выбором  одного варианта - когда выбран верный вариант.

Таблица Result - чтобы запоминать, какие тесты с какими результатами пользователь проходил.
Можно выдавать какую-нибудь статистику или не разрешать проходить один и тот же тест чаще 1 раза в сутки.

2020-12-08 07:21 UTC, BubuntuClu commented on db/migrate/20201207070228_create_results.rb
> +	def change
тут наоборот все сломалось

2020-12-08 07:21 UTC, BubuntuClu commented on db/schema.rb
> +  create_table "results", id: false, force: :cascade do |t|
это лишняя опция, ты добавила в таблицу поле, которая не служит для связывания таблиц. значит его надо будет как-то брать и обновлять, а самый простой способ получить строку по ID ты удалила. стоит вернуть

2020-12-08 07:22 UTC, BubuntuClu commented on db/seeds.rb
> +Result.create(test_id: test.id, user_id: 1)
это не поправила. user_id: 1. нужно из объекта user брать id, как ты делаешь например выше test_id: test.id

2020-12-08 07:23 UTC, BubuntuClu commented on db/migrate/20201204133610_create_interpretations.rb
> +    create_table :interpretations do |t|
из описания не понял для чего вот эта таблица.

2020-12-08 07:23 UTC, BubuntuClu commented on db/migrate/20201207070228_create_results.rb
> +			t.string :result, default: '0'
почему результат в стринге. тут прям текст какой-то будет записываться?

2020-12-08 07:25 UTC, BubuntuClu commented on db/migrate/20201204133600_create_answers.rb
> +      t.string :mark, limit: 1, default: '0'
можешь напомнить почему тут стринг и дефолтное значение 0?

вижу в таблице interpretations
t.string :mark, limit: 1, default: 'a'
это я так понял разные ответы под разные типы тестов?

2020-12-08 13:39 UTC, merged